### PR TITLE
Fix message include

### PR DESCRIPTION
**Pull request by timonegk**
Rename ROS1 include to ROS2 include.

### CODE REVIEW

**Comment by Flova** [comment]
How did this build work on my machine without ROS1 being installed?

**Comment by timonegk** [comment]
I have no idea. There was also one fix in the localization which I pushed to the nav2 branch where I also don't understand how it built on your machine...

**Comment by SammyRamone** [comment]
maybe you did not do a clean build. I also had some cases where I only realized that the build actually is failing after doing a clean build :shrug:

**Review by SammyRamone — APPROVED** [review]

**Comment by Flova** [comment]
> maybe you did not do a clean build. I also had some cases where I only realized that the build actually is failing after doing a clean build shrug

I reinstalled Ubuntu in the meantime, so I doubt any ROS1 artifacts were left.

**Pull request merged**
